---
title: "Pro Skills Basketball"
author: "Architech Sports and Physical Therapy"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r, echo=FALSE}
htmltools::img(src = knitr::image_uri("Architech+Sports+Logo.png"), 
               alt = 'logo', 
               style = 'position:absolute; top:0; right:0; padding:10px;')
```


```{r}
library(vtable)
data <- read.csv(file = 'basketball_random.csv')
sumtable(data)
```



```{r}
library(ggplot2)
library(tidyverse)
library(data.table)
#CMJ
bins <- ceiling(length(data$First)^(1/2))
melt_data <- melt(as.data.table(data[-ncol(data)]), id= c('First', 'Last'))
melt_data %>%
  ggplot(mapping = aes(x = value, group = variable)) +
  geom_density(fill = 'red', alpha = 0.5) +
  #facet_wrap(~variable, nrow = 3, ncol = 1, scales = 'free') +
  guides(group = FALSE) +
  theme_bw() + 
  theme(
    plot.title = element_text(face = "bold", size = 12),
    legend.background = element_rect(
      fill = "white", 
      linewidth = 4, 
      colour = "white"
    ),
    axis.ticks = element_line(colour = "grey70", linewidth = 0.2),
    panel.grid.major = element_line(colour = "grey70", linewidth = 0.2),
    panel.grid.minor = element_blank()
  )
```


