---
title: "Monthly Report"
format: html
editor: visual
params:
  month: 6
  year:  2024
execute: 
  echo: false
  warning: false
  cache: false
---

```{r}
library(kableExtra)
library(tidyverse)
library(ggplot2)
library(DT)

# Create file paths
raw_path   = '../data/raw/'
clean_path = '../data/clean/'

# Read data from summary_data csv
file_NAME <- paste(clean_path, params$year, '_', params$month, '_summary_data.csv'
                   , sep = '')
full_file_NAME <- paste(clean_path, params$year, '_', params$month, '_testing_data.csv', sep = '')

data           <- read.csv(file = file_NAME)
athletes       <- unique(data$NAME)
full_data      <- read.csv(file = full_file_NAME)
full_data      <- full_data[full_data$NAME %in% athletes,] %>%
                  arrange(NAME)
full_data$DATE <- as.Date(full_data$DATE)
tests          <- full_data %>%
                  select(-NAME,
                         -DATE,
                         -AGE, 
                         -IMTP_PEAK, 
                         -DATE_MONTH, 
                         -NORDBORD_L, 
                         -NORDBORD_R, 
                         -NORDBORD_DIFF, 
                         -DSI, 
                         -OLD, 
                         -YOUNG, 
                         -ADULT, 
                         -CMJ_FLIGHT) %>%
                  names()

```

::: panel-tabset
```{r}
#| output: asis
res <- purrr::map_chr(tests, \(hw) {
    knitr::knit_child('Monthly_Report_Template.qmd', envir = environment(), quiet = TRUE)
  })
cat(res, sep = '\n')

```
:::

<!-- ::: panel-tabset -->

<!-- ## CMJ -->

<!-- ```{r} -->

<!-- # Create CMJ Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$CMJ_IMP_MOM_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$CMJ_IMP_MOM, test_data$NAME) -->

<!-- data[!is.na(data$CMJ_IMP_MOM_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('CMJ')) %>% -->

<!--   mutate(CMJ_IMP_MOM_Best_perc = (CMJ_IMP_MOM_Best_perc * 100), -->

<!--          CMJ_IMP_MOM_Last_perc = (CMJ_IMP_MOM_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## Broad Jump -->

<!-- ```{r} -->

<!-- # Create Broad Jump Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$BROAD_JUMP_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$BROAD_JUMP, test_data$NAME) -->

<!-- data[!is.na(data$BROAD_JUMP_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('BROAD_JUMP')) %>% -->

<!--   mutate(BROAD_JUMP_Best_perc = (BROAD_JUMP_Best_perc * 100), -->

<!--          BROAD_JUMP_Last_perc = (BROAD_JUMP_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## IMTP -->

<!-- ```{r} -->

<!-- # Create IMTP Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$IMTP_FBW_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$IMTP_FBW, test_data$NAME) -->

<!-- data[!is.na(data$IMTP_FBW_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('IMTP_FBW')) %>% -->

<!--   mutate(IMTP_FBW_Best_perc = (IMTP_FBW_Best_perc * 100), -->

<!--          IMTP_FBW_Last_perc = (IMTP_FBW_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## Pull-Ups -->

<!-- ```{r} -->

<!-- # Create Pull-Up Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$PULL_UPS_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$PULL_UPS, test_data$NAME) -->

<!-- data[!is.na(data$PULL_UPS_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('PULL_UPS')) %>% -->

<!--   mutate(PULL_UPS_Best_perc = (PULL_UPS_Best_perc * 100), -->

<!--          PULL_UPS_Last_perc = (PULL_UPS_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## Flexed Hang -->

<!-- ```{r} -->

<!-- # Create Flex Arm Hang Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$FLEXED_HANG_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$FLEXED_HANG, test_data$NAME) -->

<!-- data[!is.na(data$FLEXED_HANG_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('FLEXED')) %>% -->

<!--   mutate(FLEXED_HANG_Best_perc = (FLEXED_HANG_Best_perc * 100), -->

<!--          FLEXED_HANG_Last_perc = (FLEXED_HANG_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## 10-Yd -->

<!-- ```{r} -->

<!-- # Create 10yd Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$SPLIT_10_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$SPLIT_10, test_data$NAME) -->

<!-- data[!is.na(data$SPLIT_10_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('SPLIT_10')) %>% -->

<!--   mutate(SPLIT_10_Best_perc = (SPLIT_10_Best_perc * 100), -->

<!--          SPLIT_10_Last_perc = (SPLIT_10_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## 20-Yd -->

<!-- ```{r} -->

<!-- # Create 20yd Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$SPRINT_20_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$SPRINT_20, test_data$NAME) -->

<!-- data[!is.na(data$SPRINT_20_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('SPRINT_20')) %>% -->

<!--   mutate(SPRINT_20_Best_perc = (SPRINT_20_Best_perc * 100), -->

<!--          SPRINT_20_Last_perc = (SPRINT_20_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## 5-10-5 -->

<!-- ```{r} -->

<!-- # Create 20yd Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$PRO_AGILITY_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$PRO_AGILITY, test_data$NAME) -->

<!-- data[!is.na(data$PRO_AGILITY_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('PRO_AGILITY')) %>% -->

<!--   mutate(PRO_AGILITY_Best_perc = (PRO_AGILITY_Best_perc * 100), -->

<!--          PRO_AGILITY_Last_perc = (PRO_AGILITY_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## 300-Yd -->

<!-- ```{r} -->

<!-- # Create 300yd Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$SHUTTLE_300_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$SHUTTLE_300, test_data$NAME) -->

<!-- data[!is.na(data$SHUTTLE_300_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('SHUTTLE_300')) %>% -->

<!--   mutate(SHUTTLE_300_Best_perc = (SHUTTLE_300_Best_perc * 100), -->

<!--          SHUTTLE_300_Last_perc = (SHUTTLE_300_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## Yo-Yo -->

<!-- ```{r} -->

<!-- # Create Yo-Yo Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$YO_YO_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$YO_YO, test_data$NAME) -->

<!-- data[!is.na(data$YO_YO_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('YO_YO')) %>% -->

<!--   mutate(YO_YO_Best_perc = (YO_YO_Best_perc * 100), -->

<!--          YO_YO_Last_perc = (YO_YO_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ## Nordbord -->

<!-- ```{r} -->

<!-- # Create Nordbord Table -->

<!-- test_athletes <- unique(data$NAME[!is.na(data$NORDBORD_Current)]) -->

<!-- test_data <- full_data[full_data$NAME %in% test_athletes,] -->

<!-- split_data <- split(test_data$NORDBORD, test_data$NAME) -->

<!-- data[!is.na(data$NORDBORD_Current),] %>% -->

<!--   cbind('Trend' = '') %>% -->

<!--   select( -->

<!--     NAME, -->

<!--     Trend, -->

<!--     starts_with('NORDBORD')) %>% -->

<!--   mutate(NORDBORD_Best_perc = (NORDBORD_Best_perc * 100), -->

<!--          NORDBORD_Last_perc = (NORDBORD_Last_perc * 100)) %>% -->

<!--   kable( -->

<!--     digits = 2, -->

<!--     row.names = FALSE, -->

<!--     col.names = c('NAME', -->

<!--                   'Trend', -->

<!--                   'Current', -->

<!--                   'Best', -->

<!--                   'Best Change', -->

<!--                   'Best % Change', -->

<!--                   'Previous', -->

<!--                   'Previous Change', -->

<!--                   'Previous % Change' -->

<!--                   ) -->

<!--   ) %>% -->

<!--   kable_styling( -->

<!--     full_width = TRUE, -->

<!--     fixed_thead = TRUE -->

<!--   ) %>% -->

<!--   column_spec(2, image = spec_plot(split_data, same_lim = FALSE)) -->

<!-- ``` -->

<!-- ::: -->
